<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net462</TargetFrameworks>
    <DefineConstants>CORE</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="TestResults\**" />
    <EmbeddedResource Remove="TestResults\**" />
    <None Remove="TestResults\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\PdfSharp\PdfSharp.csproj" />
  </ItemGroup>

</Project>
